sudo: required

language: php

services:
  - mysql

php:
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - sudo mkdir -p /opt/local/var/run/mysql57/
  - echo -e "[server]\nsocket=/opt/local/var/run/mysql57/mysqld.sock" | sudo tee -a ~travis/.my.cnf
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE test_packages_blog;'

install:
  - travis_retry composer update --prefer-source $COMPOSER_FLAGS
  - travis_retry composer require league/flysystem-aws-s3-v3

script:
  - vendor/bin/phpunit

branches:
  only:
    - master

